server:
  port:
    8080

spring:
  datasource:
    url: jdbc:mysql://114.55.235.198/fatty_corps?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Zaoan9984..
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印